workflows:
    ionic-capacitor-ios:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
    environment:
        vars:
            XCODE_WORKSPACE: "platforms/ios/YOUR_APP.xcworkspace"
            XCODE_SCHEME: "YOUR_SCHEME"
    scripts:
        Install npm dependencies for Ionic project: |
            brew install pkg-config && npm ci
        Build: |
            npm run build:ios
        Build ipa for distribution: |
            cd $CM_BUILD_DIR/ios/App
            xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"