workflows:
  ionic-capacitor-ios:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
  scripts:
    - name: Install npm dependencies for Ionic project
      script: |
        brew install pkg-config && npm ci
    - name: Build
      script: |
        npm run build:ios
    - name: Build ipa for distribution
      script: |
        cd $CM_BUILD_DIR/ios/App
        xcode-project build-ipa \
          --workspace "$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"